/// Flutter icons BottomNavigationBar
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavigationBar
///      fonts:
///       - asset: fonts/BottomNavigationBar.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BottomNavigationBarIcons {
  BottomNavigationBarIcons._();

  static const _kFontFam = 'BottomNavigationBarIcons';
  static const String? _kFontPkg = null;

  static const IconData ic_myrent = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_myrent_active = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_offer = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_offer_active = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile_active = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home_active = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
