/// Flutter icons BubbleBottomNavigationBarIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BubbleBottomNavigationBarIcons
///      fonts:
///       - asset: fonts/BubbleBottomNavigationBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BubbleBottomNavigationBarIcons {
  BubbleBottomNavigationBarIcons._();

  static const _kFontFam = 'BubbleBottomNavigationBarIcons';
  static const String? _kFontPkg = null;

  static const IconData ic_calendar_active = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile_active = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__calendar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__statistic = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__statistic_active = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home_active = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
